const disData=[
    "Bengaluru Urban",
    "Bengaluru Rural",
    "Mysuru",
    "Ballari",
    "Dakshina Kannada",
    "Hassan",
    "Belagavi",
    "Udupi",
    "Tumakuru",
    "Davanagere",
    "Shivamogga",
    "Dharwad",
    "Kalaburagi",
    "Mandya",
    "Koppal",
    "Raichur",
    "Bagalkote",
    "Uttara Kannada",
    "Vijayapura",
    "Chitradurga",
    "Chikkamagaluru",
    "Chikkaballapura",
    "Gadag",
    "Haveri",
    "Yadgir",
    "Kolar",
    "Ramanagara",
    "Bidar",
    "Chamarajanagara",
    "Kodagu",
 ]
disData.sort();
 export default disData;